version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: news-db
    environment:
      MYSQL_ROOT_PASSWORD: contrase単a_root
      MYSQL_DATABASE: inventory_sales_db
      MYSQL_USER: usuario_db
      MYSQL_PASSWORD: contrase単a_segura
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - news-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: news-api
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=usuario_db
      - DB_PASS=contrase単a_segura
      - DB_NAME=inventory_sales_db
      - DB_ROOT_PASSWORD=contrase単a_root
      - JWT_SECRET=izi_ventas_secret
      - PORT=8082
    ports:
      - "8082:8082" # Change the exposed port to 8082
    depends_on:
      db:
        condition: service_healthy
    networks:
      - news-network
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  news-network:
    driver: bridge